@startuml
'https://plantuml.com/component-diagram

node "Client" {
    [Browser]
}

        () HTTPS

node "Zuchtbuch Online" {

    component Apache/PHP {
        [API]
        [SPA]
    }

    () SQL
    database MySQL
}

Browser -d-> HTTPS
SPA <-u- HTTPS
API <-u- HTTPS
API -d-> SQL
MySQL <-u- SQL


@enduml