@startuml

class User #FFFFAA
class Breeder #FFFFAA
class Moderator #FFFFAA
class Admin #FFFFAA
class Club #AAFFFF
class District #AAFFFF
class Section #AAFFAA
class Breed #AAFFAA
class Color #AAFFAA
class Animal {
    country
    year
    ring
    score
}

class Result #AAAAFF {
    year
    lay_dames
    lay_eggs
    lay_weight
    brood_eggs
    brood_fertile
    brood_hatched
    show_animals
    show_score
    show
}
class Pair #FFAAFF {
    name
    paired:date
}
class Parent #FFAAFF {

}
class Lay #FFAAFF
class Brood #FFAAFF {
    start:date
    eggs
    fertile
    hatched
}
class Show #FFAAFF {
    animals
    scores
}

class Pages


User <-l- Breeder : is
User <-d- Moderator : is
User <-u- Admin : is

Moderator -l-> District : moderates

Parent --> Animal : is

Breed -r-> Section : of
Color -r-> Breed : of


Pair -r-> "1" Result : with
Pair <-l- "*" Parent : in
Pair <-d- "*"  Lay
Pair <-d- "*" Brood
Pair <-d- "*" Show
Pair <-l- "*" Animal : child of

Result -> Breeder : of
Result -> District : of
Result -u-> Breed
Result -u-> Color


Breeder --> Club : member
Club --> District


Section -> Section
District -> District
@enduml